pipeline {
    agent any

    stages {
        stage('Check Files') {
            steps {
                sh 'ls -al demo'
            }
        }

        stage('Build') {
            steps {
                dir('demo') {
                    sh 'chmod +x gradlew'   // gradlew 실행 권한 부여
                    sh './gradlew clean build'
                }
            }
        }

        stage('Notify') {
            steps {
                script {
                    def payload = """
                    {
                        "jobName": "deploy-service-a",
                        "eventType": "BUILD_SUCCESS",
                        "message": "✅ 빌드 성공!"
                    }
                    """

                    httpRequest(
                        httpMode: 'POST',
                        contentType: 'APPLICATION_JSON',
                        requestBody: payload,
                        url: 'http://localhost:8080/notifications/notify'
                    )
                }
            }
        }
    }
}
