pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('demo') {
                    sh 'chmod +x gradlew'  // 권한 문제 방지
                    sh './gradlew clean build -x test'  // 테스트 제외 빌드
                }
            }
        }

        stage('Notify') {
            steps {
                script {
                    def payload = """
                    {
                        "jobName": "deploy-service-a",
                        "eventType": "BUILD_SUCCESS",
                        "message": "✅ 빌드 성공!"
                    }
                    """

                    httpRequest(
                        httpMode: 'POST',
                        contentType: 'APPLICATION_JSON',
                        requestBody: payload,
                        url: 'http://1.221.229.38:8080/notifications/notify'
                    )
                }
            }
        }
    }
}
