pipeline {
    agent any

    stages {
        stage('Build') {
             steps {
                    echo '의도적으로 실패 테스트 중...'
                    sh 'exit 1'  // 0이 아닌 값을 리턴하면 실패 처리됨
             }
        }
    }

    post {
        success {
            script {
                def jobName = env.JOB_NAME
                def buildNumber = env.BUILD_NUMBER
                def buildUrl = env.BUILD_URL

                def message = "✅ 빌드 성공! Job: ${jobName} Build: #${buildNumber} 빌드 확인: ${buildUrl}"

                sh "curl -H 'Content-Type: application/json' -X POST -d '{\"content\": \"${message}\"}' https://discord.com/api/webhooks/1386017644993318952/jmjtLjeTUu7iP1slpKfMDPVkoAvBSWCtzx8E2JhDt9WW7wdGxHi2Ob_BsoWMR_GuVQw7"
            }
        }
        failure {
            script {
                def jobName = env.JOB_NAME
                def buildNumber = env.BUILD_NUMBER
                def buildUrl = env.BUILD_URL

                def message = "❌ 빌드 실패! Job: ${jobName} Build: #${buildNumber} 빌드 확인: ${buildUrl}"

                sh "curl -H 'Content-Type: application/json' -X POST -d '{\"content\": \"${message}\"}' https://discord.com/api/webhooks/1386017644993318952/jmjtLjeTUu7iP1slpKfMDPVkoAvBSWCtzx8E2JhDt9WW7wdGxHi2Ob_BsoWMR_GuVQw7"
            }
        }
    }
}
